name: Bug Report
description: File a bug report.
labels: ['bug']
body:
- type: markdown
  attributes:
    value: |
      We encourage using GitHub as a centralized place for community engagement. Please complete the following before submitting your issue:

      - Read the [contributing guidelines](https://github.com/WhaleConnect/whaleconnect/blob/main/docs/CONTRIBUTING.md).
      - Search for [past issues](https://github.com/WhaleConnect/whaleconnect/issues?q=) to check for similar discussions.

      Thank you for taking the time to complete these steps and fill out this issue form.

- type: textarea
  attributes:
    label: WhaleConnect Build Info
    description: Go to "Help > About" in WhaleConnect, click Copy, and paste it here.
  validations:
    required: true

- type: input
  attributes:
    label: Operating System
    description: What OS are you using? Include (if applicable) - Windows OS version and edition (Settings > System > About), macOS version (Apple menu > About this Mac), Linux distro and kernel version (lsb_release, uname -a).
  validations:
    required: true

- type: input
  attributes:
    label: CPU Architecture
    description: What is your CPU architecture? WhaleConnect supports specific OS and architecture combinations, listed in the readme. If you have a custom build for an unsupported combination, indicate that as well - though we may not be able to fully provide support in these cases.
  validations:
    required: true

- type: textarea
  attributes:
    label: Bug Description
    description: A concise and detailed description of the current behavior and what you expected. Include screenshots/screen recordings to aid in your description.
  validations:
    required: true

- type: textarea
  attributes:
    label: Environment/Settings Configuration
    description: Any setup that you believe could influence this behavior.
